import { Navigate, useParams } from 'react-router-dom'
import { BlogArticle } from '@/components/blog/BlogArticle'
import { getPost, type BlogPost as Post } from '@/data/blog'
import { usePageMeta } from '@/lib/usePageMeta'

/**
 * Published blog post — Figma node 2168:70798. Content comes from the build
 * manifest generated by scripts/fetch-content.ts.
 */

function Article({ post }: { post: Post }) {
  // `post.image` is already an absolute CMS URL, which is what social crawlers
  // require — no origin prefix.
  usePageMeta(`${post.title} | Stablezact`, post.metaDescription, {
    image: post.image,
    type: 'article',
  })

  return <BlogArticle post={post} />
}

export default function BlogPost() {
  const { slug } = useParams()
  const post = getPost(slug)

  if (!post) return <Navigate to="/blog" replace />
  return <Article post={post} />
}
